# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-20.04
  tools:
    python: mambaforge-4.10
  jobs:
    pre_build:
      - pip install sphinx_press_theme==0.9.1

conda:
  environment: docs/environment.yml

sphinx:
  configuration: docs/source/conf.py
  # fail_on_warning: true